### ISSUE TITLE
Plugin detection problems

### ISSUE THREAD

**Issue by J12934** [wpscanteam/wpscan-v3#10]
Hi,
I am having detecting the plugins of a site using the v3 Scanner.

The v2 of the wpscanner managed to find multiple Plugins of a site while the v3 scanner wasn't able to find any.

Is the plugin detection functionality unfinished in v3?
Or might this be related to changes in the default settings.
Or is this 'just' a bug?

Command used in v2:
`docker run --rm wpscanteam/wpscan --url https://www.(domainname).de/ --update`

Command used in v3:
`docker run --rm wpscanteam/wpscan-v3 --url https://www.(domainname).de/ --update`

I also tried changing `--detection-mode` to aggressive but that did not help either.

Thank you in advance ;)

**Comment by erwanlr** [comment]
You need to use the --enumerate/-e option

**Comment by J12934** [comment]
Thank you!
Working fine now.
