### ISSUE TITLE
Append output content

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan-v3#12]
Needed to scan multiple targets and used the ```-o``` option to output to file. But the file content was overwritten after each scan, instead of appending the results.

Do you think it would be possible to append to the file rather than overwrite?

For example, if you run WPScan twice with the same output file name, the output file will only contain the results from the last scan:

```wpscan --url www.example.com -f json -o out.json```
```wpscan --url www.example2.com -f json -o out.json```

**Comment by erwanlr** [comment]
Not sure it's a good idea as in the JSON case, the final file would be malformed ;p

**Comment by ethicalhack3r** [comment]
Good point. Can always use ```>>``` for this situation anyway
