### ISSUE TITLE
unable to detect version 4.7.3

### ISSUE THREAD

**Issue by eb-ldelfin** [wpscanteam/wpscan-v3#13]
I recently upgraded WP to 4.7.3 due to some security fixes.  wpscan-v3 is currently unable to detect this version and returns version 2.2 via Homepage Stylesheet Numbers (Passive Detection)

**Comment by erwanlr** [comment]
Do you still have the issue after running ```wpscan --update``` ?

**Comment by eb-ldelfin** [comment]
Looks fixed now. Thanks!
