### ISSUE TITLE
unable to determine theme in aggressive mode, detects incorrect version of WordPress in all modes

### ISSUE THREAD

**Issue by gilzow** [wpscanteam/wpscan-v3#14]
Playing with the new version of wpscan.  If I leave the detection mode in its default of mixed, or set it to passive, wpscan is able to determine my theme (twentyseventeen v1.1).  If I change the detection-method to aggressive, it is unable to determine the theme: "The main theme could not be detected."

In all detection modes, it is incorrectly determining the WordPress version to be 2.1.2 based on wp-content/themes/twentyseventeen/assets/js/jquery.scrollTo.js?ver=2.1.2 even though the correct version number is appended to numerous plugin css files as well as wp-embed.min.js, style.css, etc. 

What additional information do you need from me in order to help you troubleshoot?

**Comment by erwanlr** [comment]
wpscan --update will solve the WP detection.

regarding the main theme, it's normal. As the CSS file is resent in the homepage, the passive detection grabs it and find the version from that. With aggressive, this is not done (only aggressive methods are used, passive ignored, mixed mode uses passive + aggressive)
