### ISSUE TITLE
User Enumeration Error

### ISSUE THREAD

**Issue by diablodaz** [wpscanteam/wpscan-v3#16]
Long time listener, first time caller.

I get the following error when using the 'enumeration users' command:

wpscan -e u --url <URL>
[+] Enumerating Users
Scan Aborted: undefined method `each' for nil:NilClass

**Comment by erwanlr** [comment]
Are you running the latest version (3.0.3) ?

If so, could you send us the url of the target of investigation please ? team at wpscan dot org

**Comment by erwanlr** [comment]
Never had this one. Feel free to reopen if you still have it

**Comment by ScatteredThoughts** [comment]
I'm also getting the same error when trying to enumerate users for a particular site. This is with version 3.0.8.

**Comment by erwanlr** [comment]
Could you send us the url for investigation please ? team at wpscan dot org

**Comment by erwanlr** [comment]
Thanks @ScatteredThoughts for sending the URL, this is now fixed and you should be good to go with the new docker image once it has been rebuilt :)
