### ISSUE TITLE
Passive plugin detection and version detect

### ISSUE THREAD

**Issue by RcDS** [wpscanteam/wpscan-v3#17]
Hi, I am attempting to perform passive plugin detection and once a plugin is discovered, perform version detection checks (without attempting to check all known plugin locations). I believe this is the default behaviour of WPScan v2, but I'm currently having trouble replicating this in v3. 

I would have thought that the options below would perform the process described above, however whilst it displays the passively identified plugins it does not perform the version checks. 

 `--enumerate p --plugins-detection passive --plugins-version-all` 

Is there something I'm missing?

**Comment by erwanlr** [comment]
The --plugins-version-all depends on the --plugins-detection or --detection-mode but this wasn't put in the help of the option. 

Might need to add a --plugins-version-detection option maybe to match such need

**Comment by RcDS** [comment]
Ah I see - no problem! 

A separate option for this would be extremely useful if its a quick addition :)

**Comment by vikasprogrammer** [comment]
+1 

(relates to my [issue](https://github.com/wpscanteam/wpscan-v3/issues/25))

**Comment by erwanlr** [comment]
I gave the new options --plugin|theme-versions-detection a try, not as easy as I thought to implement :x

Will continue to think about it

**Comment by erwanlr** [comment]
Fixed, see https://github.com/wpscanteam/wpscan-v3/issues/25
