### ISSUE TITLE
Fixnum is deprecated Bignum is deprecated

### ISSUE THREAD

**Issue by planetahuevo** [wpscanteam/wpscan-v3#19]
I am getting this error when trying to execute wpscan-v3 from docker:
`/usr/local/bundle/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/usr/local/bundle/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/usr/local/bundle/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
`

**Comment by erwanlr** [comment]
Unable to reproduce, feel free to reopen the issue if you still have it
