### ISSUE TITLE
Does not detect if Plugin version is outdated

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan-v3#2]
WPScan v2 outputs if a detected Plugin version is outdated or not, as well as the date it was last updated.

This functionality/information is missing from WPScan v3.

**Comment by erwanlr** [comment]
The v2 never output the last update date btw, there is typo xD (https://github.com/wpscanteam/wpscan/blob/f3cc35bd74cf5d91774fd0bcafda8e6f8d849c98/lib/common/models/wp_item.rb#L54)

**Comment by ethicalhack3r** [comment]
:P this is why I should write more specs

**Comment by FireFart** [comment]
@erwanlr @ethicalhack3r haha fail :D I just fixed the typo
