### ISSUE TITLE
Use latest stable version in the Docker container

### ISSUE THREAD

**Issue by erwanlr** [wpscanteam/wpscan-v3#31]
@FireFart, could you please change the Dockerfile to use the latest stable version of the gem rather than master branch (as it might contain breaking changes like currently) ?

**Comment by FireFart** [comment]
@erwanlr what do you mean exactly? I think the benefit of the Dockerfile is to always have the latest stuff in there. If you want to have a "stable" branch you could create a branch on github and it should automatically build. So if you create a "stable" branch it should tag a docker image named "wpscanteam/wpscan-v3:stable" automatically

**Comment by erwanlr** [comment]
I mean install WPScan v3 from gem install rather than the master branch in the Docker.

Currently, the master branch is not usable/stable as there are breaking changes (due to the format of the dynamic finders file which changed)

**Comment by FireFart** [comment]
The current build is set up as an auto trigger build from master which I wouldn‘t change. That’s why the image is tagged with latest :)
I would create a separate branch with the stable version and create a separate docker image from there
