### ISSUE TITLE
hang after plugin scan completes

### ISSUE THREAD

**Issue by zachsis** [wpscanteam/wpscan-v3#40]
I have a site in my environment that wpscanv3 is hanging on indefinitely after the plugin scan finishes. Is there a way to get more debug output than `-v` ? 

```
$ git describe --tags
v3.0.8-52-g51675b1
```

```
[+] Enumerating Vulnerable Plugins
 Checking Known Locations - Time: 00:00:08 <===========================================================================================> (1579 / 1579) 100.00% Time: 00:00:08

^C^C^C^C^C^C^C^CScan Aborted: Canceled by User
Trace: /home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/ffi-1.9.18/lib/ffi/pointer.rb:51:in `read_string'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/ethon-0.11.0/lib/ethon/easy/callbacks.rb:54:in `block in header_write_callback'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/ethon-0.11.0/lib/ethon/easy/operations.rb:29:in `easy_perform'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/ethon-0.11.0/lib/ethon/easy/operations.rb:29:in `perform'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/typhoeus-1.3.0/lib/typhoeus/request/operations.rb:16:in `run'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/typhoeus-1.3.0/lib/typhoeus/request/cacheable.rb:18:in `run'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/typhoeus-1.3.0/lib/typhoeus/request/block_connection.rb:31:in `run'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/typhoeus-1.3.0/lib/typhoeus/request/stubbable.rb:25:in `run'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/typhoeus-1.3.0/lib/typhoeus/request/before.rb:26:in `run'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner/browser/actions.rb:44:in `process'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner/browser/actions.rb:10:in `get'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/app/finders/plugin_version/readme.rb:12:in `block in aggressive'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/app/finders/plugin_version/readme.rb:10:in `each'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/app/finders/plugin_version/readme.rb:10:in `aggressive'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner/finders/base_finders.rb:28:in `run_finder'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner/finders/unique_finders.rb:20:in `block (2 levels) in run'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner/finders/unique_finders.rb:19:in `each'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner/finders/unique_finders.rb:19:in `block in run'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner/finders/unique_finders.rb:18:in `each'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner/finders/unique_finders.rb:18:in `run'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner/finders/independent_finder.rb:19:in `find'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner/finders/independent_finder.rb:10:in `find'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/app/models/plugin.rb:20:in `version'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/app/controllers/enumeration/enum_methods.rb:55:in `each'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/app/controllers/enumeration/enum_methods.rb:55:in `enum_plugins'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/app/controllers/enumeration.rb:16:in `run'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner/controllers.rb:42:in `each'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner/controllers.rb:42:in `run'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner.rb:101:in `run'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/bin/wpscan:14:in `block in <top (required)>'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/cms_scanner-0.0.38.1/lib/cms_scanner.rb:92:in `initialize'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/bin/wpscan:5:in `new'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/gems/wpscan-3.0.8/bin/wpscan:5:in `<top (required)>'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/bin/wpscan:23:in `load'
/home/me/.rvm/gems/ruby-2.3.3@wpscanv3/bin/wpscan:23:in `<main>'
^C^C
```

**Comment by erwanlr** [comment]
After checking the plugins/themes, their versions is checked to determine whether or not they are vulnerable. Depending on the number of items detected, it may take a while :/.

I will add a message like "xxxx Plugins identified, determining their version for vulnerabilities"

This would help in the case of a high number of plugins identified, which would be dubious and probably related to a security plugin/hardening producing false positive.

**Comment by zachsis** [comment]
@erwanlr we dont have a *ton* of plugins on this site.. I actually let it sit for over 24 hours in a screen session and it never finished. I'm happy to help debug further but need a little direction of what you need.

**Comment by erwanlr** [comment]
You can use the --proxy option to proxy the requests through burp for example, to see what's going on

**Comment by zachsis** [comment]
good thinking. thx

**Comment by erwanlr** [comment]
Oh, and if you don't want to re-check all the plugins (or have identified a specific one messing around), you can use the --plugins-list option (along with he --enumerate), with either a single plugin slug, or coma separated ones, or a file path.

e.g.:
```-e ap --plugins-list wordpress-seo```
```-e ap --plugins-list wordpress-seo,wordfence```
```-e ap --plugins-list /path-to/a-file.txt```

Might save you some time ;)

**Comment by zachsis** [comment]
if you use the txt file is it comma separated or `\n`?

**Comment by erwanlr** [comment]
```\n```

**Comment by zachsis** [comment]
Awesome this works, but have you run into issues where a plugin exists on wpvulndb, but when wpscan tries to enumerate the plugin it doesn't find it, even when you can hit the readme.txt file directly? I'm seeing this on our site with `google-sitemap-generator` for example and a few other plugins which I've defined in a text file. 

https://wpvulndb.com/api/v2/plugins/google-sitemap-generator

Ran with the following: 

`wpscan --url "$SITE" -e ap --plugins-list "$PLUGINLISTPATH"/mypluginlist.txt -f json`

**mypluginlist.txt:**
```
akismet
all-in-one-seo-pack
googleanalytics
google-sitemap-generator
missed-schedule
wordpress-importer
wp-pagenavi
```

wpscan detects the following: 
```
akismet
all-in-one-seo-pack
wp-pagenavi
```

**Comment by erwanlr** [comment]
Really depends on the configuration of the blog, hardening, security plugins used & configured and so on.

Readmes are not checked for plugin detection so far (only once a plugin is detected, for its version). Plugins are detected via:

- Comments in the homepage
- Headers
- URLs in the homepage (like wp-content/plugins/all-in-one-seo-pack/)
- Direct access to the plugin directory (which is the most difficult part to handle, as some plugins redirect to the homepage, others have a blank page, 401. And, on top of that, you have the behaviour of potential .htaccess, security plugins etc which can screw things over :x)

(See https://github.com/wpscanteam/wpscan-v3/tree/v3.0.8/app/finders/plugins for the related code). I've already implemented more detection methods in the master branch, which will land in the 3.1.0, and will improve all this stuff.

If you own the blogs, any particular reason to use wpscan over a plugin to check for vulnerable outdated plugins (which will be more accurate than wpscan) ?

**Comment by zachsis** [comment]
@erwanlr yeah I'm thinking thats going to be the route I end up going at $dayjob, and just use wpscan for pentest engagements. Thanks! I'll close this now.
