### ISSUE TITLE
Always detect plugin [sitepress-multilingual-cms]

### ISSUE THREAD

**Issue by javiercasares** [wpscanteam/wpscan-v3#45]
Since some days ago every scan I do gets this plugin: sitepress-multilingual-cms.

Everytime it says:

/wp-content/plugins/sitepress-multilingual-cms/changelog.md Match: '#038'

changing the "version" it found. In every case, this plugin does not exists.

**Comment by erwanlr** [comment]
Please run ```wpscan --update``` and retry. Not sure it will fix the issue though, so let me know.

A new docker image is being built, in case your are using it.

**Comment by javiercasares** [comment]
Seems to be fixed :)
