### ISSUE TITLE
Database update failing

### ISSUE THREAD

**Issue by harry-m** [wpscanteam/wpscan-v3#49]
Hello,

I'm currently unable to update wpscan-v3's database:

> root@a22c1531c514:/app# wpscan --update
> [snip]
>
> [i] Updating the Database ...
> Scan Aborted: Unable to get https://data.wpscan.org/wordpress.db.sha512 (status: 403)
> root@a22c1531c514:/app# 

When I request it in a browser I get back "ERROR" as a body, and nothing else. This is from a fresh clone of the repo.

Has something broken, or am I doing something wrong?

**Comment by erwanlr** [comment]
Seems like you are running a version < 3.0.8. Please update using ```gem update wpscan```.

**Comment by harry-m** [comment]
Thanks - you're quite right. Sorry for the duff issue. Looks like (inevitably) there's a problem in my docker config.
