### ISSUE TITLE
Plugin Scans Not Working

### ISSUE THREAD

**Issue by adnanmueller** [wpscanteam/wpscan-v3#5]
Plugin enumeration options (vp, p, ap) result in the scan completing but then coming back with an error `Scan Aborted: undefined method 'confidence' for #<Array:0x00563a3550ec98>`

**Comment by erwanlr** [comment]
Can't reproduce, do you have the full command that you ran ? Or with all
the options ? You can send the target URL to team@wpsan.org if needed, that
would help

**Comment by erwanlr** [comment]
Team@wpscan.org*

**Comment by adnanmueller** [comment]
the issue happens when i just use a command like wpscan --url xxx -e p
I will send the url in an email

**Comment by erwanlr** [comment]
```gem update wpscan``` and you are good to go :)
