### ISSUE TITLE
Version detection bug?

### ISSUE THREAD

**Issue by harry-m** [wpscanteam/wpscan-v3#50]
I'm getting lots of incorrect version results in scans, characterised by wpscan returning a result based on a stylesheet version number, where that is the only result returned, but where a much better (accurate) version is easily determinable. This is on 3.1.0.

For example -> http://romsleyparishcouncil.gov.uk/

My wpscan result says 3.2.1, based on the numbers in the stylesheet URLs, but the HTML contains a generator tag that identifies the version as 4.8.3. My command line includes ```--wp-version-detection=passive``` but I can't imagine wpscan would treat detection of a generator tag as aggressive.

I've tried to investigate this but I'm finding the codebase a bit confusing! Happy to pitch in if there are more things I can check/clarify.

**Comment by erwanlr** [comment]
Could you provide the cli command used ?

Using the 3.1.0 along with the latest db update (```wpscan --update```), and running ```wpscan --stealthy --url http://romsleyparishcouncil.gov.uk/``` or ```wpscan --url http://romsleyparishcouncil.gov.uk/```, I have the below:

```
[+] WordPress version 4.8.3 identified.
 | Detected By: Emoji Settings (Passive Detection)
 |  - http://romsleyparishcouncil.gov.uk/, Match: 'wp-includes\/js\/wp-emoji-release.min.js?ver=4.8.3'
 | Confirmed By: Meta Generator (Passive Detection)
 |  - http://romsleyparishcouncil.gov.uk/, Match: 'WordPress 4.8.3'
```

As most of the detection methods are put in the DB, make sure to update it before scanning ;)

**Comment by harry-m** [comment]
Hey, just an update - I am still getting inconsistent results but my original report is not correct, and I haven't got to the bottom of it yet. So, sorry for another bogus issue! I'll close this now and re-open it with working replication steps if I work some out.
