### ISSUE TITLE
Scan Aborted: undefined method `dig' for #<String:0x00555da65d2218>

### ISSUE THREAD

**Issue by EgeBalci** [wpscanteam/wpscan-v3#52]
Started the scan with `wpscan --url site.com -ap` after finising checking known locations stage i get this 

have any idea why ?

![image](https://user-images.githubusercontent.com/17179401/35963169-f3eb516e-0cc4-11e8-818b-c59182cae1f5.png)

I installed the tool with gem and ran on a ubuntu.

**Comment by erwanlr** [comment]
May I ask you to re-run the scan with the -v option so the stack trace is output please ?

**Comment by erwanlr** [comment]
Found the issue!
