### ISSUE TITLE
SETUP TO RUN DOCKER WITH DATABASE PERSISTENCE AND DOSKEY (SHORTCUT) - WINDOWS

### ISSUE THREAD

**Issue by mvmendes** [wpscanteam/wpscan-v3#58]
-- Create volume 
-- Run container without --rm option, include -d option
-- Create a bat file to execute docker start & exec
-- Create a shortcut to bat using doskey
-- In first execution: anwser "Y" in order to update database. 
```
docker volume create wpscan_data
docker run -d -ti  --volume wpscan_data --name wpscan wpscanteam/wpscan-v3 --url http://foo.bar
echo @echo off ^&^& docker start wpscan ^&^& docker exec -ti wpscan sh -c ^"/wpscan/bin/wpscan ^%^* > wpscan.bat
doskey wpscan=%cd%\wpscan.bat $*
```

Usage:
`wpscan --url http://foo.bar`

**Comment by FireFart** [comment]
Should this be an issue report?

**Comment by mvmendes** [comment]
Sorry for this, it's more an suggestion of use, it annoys me when I need to
update database in every use with "docker run --rm" command.

2018-03-02 6:00 GMT-03:00 Christian Mehlmauer <notifications@github.com>:
