### ISSUE TITLE
Fix Gem Size

### ISSUE THREAD

**Issue by erwanlr** [wpscanteam/wpscan-v3#6]
related to https://github.com/wpscanteam/wpscan-v3/commit/4308aca1aa0c5a0e8a217312e9a3ae22ecefe07b#commitcomment-20682282

**Comment by FireFart** [comment]
@erwanlr Problem solved; https://github.com/wpscanteam/wpscan-v3/commit/14aa843bcdfe2fa5d1790c6b8bc4a8d9e1ad4bce
The git ls ignored all entries from the .gitignore which were missing.

Can you please do a `rake build` on your machine and check with the following?

```
cd pkg
tar xvf wpscan-3.0.2.gem
tar xzvf data.tar.gz
ls -al
```
