### ISSUE TITLE
redirect follow

### ISSUE THREAD

**Issue by Ondrysak** [wpscanteam/wpscan-v3#60]
seems like redirect is not working as described in previous issue
https://github.com/wpscanteam/wpscan-v3/issues/38

`wpscan --url=http://martinspub.cz/
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 3.2.1
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

Scan Aborted: The URL supplied redirects to http://www.martinspub.cz/. Use the --ignore-main-redirect option to ignore the redirection and scan the target.`

**Comment by erwanlr** [comment]
I've updated my comment on the previous issue, as the part about the sub-domains was wrong and they are considered out of scope, unless you supply the scope option with ```--scope *.domain.tld```, so in your case ```--scope *.martinspub.cz``` or ```--scope www.martinspub.cz```. You can also just provide the correct url, ie ```--url http://www.martinspub.cz/```

**Comment by Ondrysak** [comment]
yeah I sure can handle the redirection myself, but having --follow-redirect option would be nice to have :) cheers
