### ISSUE TITLE
sql backup file check

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan-v3#62]
Same as wpscan v2:
https://github.com/wpscanteam/wpscan/commit/0e73774bd9f6d13c8194e44b9b799d3e5dd089ca

Blog post with research coming soon.

Research conclusions:

> Out of the 852,301 (85%) of sites that we were able to check, we identified that 736 (0.086%) of them were exposing their database export files publicly with the same name as their domain. This may not seem like a lot, but when you consider the impact of the database contents being exposed to malicious actors, it is a considerable risk to the affected individual sites, and their users.

> Out of the 736 affected sites, 290 (39%) of them, were running WordPress.

**Comment by javiercasares** [comment]
It should try:
- {domainname}.sql
- {domainname}.sql.gz
- {domainname}.zip
- db.sql
- site.sql
- database.sql
- data.sql
- dump.sql
- db_backup.sql
- dbdump.sql
- wordpress.sql
- mysql.sql

in / , /backup/ and /backups/

**Comment by ethicalhack3r** [comment]
Thanks for the list @javiercasares! I think it would be a good idea to implement them all, but I will wait for others' feedback before implementing them.

The ```{domainname}.sql``` idea came from your WP-CLI talk :)

Research published here https://blog.dewhurstsecurity.com/2018/06/07/database-sql-backup-files-alexa-top-1-million.html

**Comment by erwanlr** [comment]
In the v3, I would implement this either as an interesting finding or add
an enumeration for this (or maybe add them in the config backup enumeration)

**Comment by erwanlr** [comment]
I would go to add an enumeration option, for those db export (any idea for the name of the option ?), enabled by default rather than an interesting finding.

Thoughts ?

**Comment by ethicalhack3r** [comment]
```db-exports``` maybe?
