### ISSUE TITLE
Wrong version detection when readme.html exists

### ISSUE THREAD

**Issue by anantshri** [wpscanteam/wpscan-v3#7]
Hi team, when Readme.html file exists on the server its used for confirmed detection of version (in absense of generator tag i suppose) however when you look at the latest versions of Wordpress Readme.html is not showing third level version so for all 4.7 4.7.1 and 4.7.2 its 4.7.

this results in detection of version as 4.7 and hence the whole long output of all vuln's fixed between 4.7 - 4.7.2 

I suppose with these changes in mind readme is not the best way to get wordpress versions now

**Comment by erwanlr** [comment]
Do you have a target to try on ?

I think you could use the --wp-version-all option, but I will reduce the confidence of the readme check (currently 90%)

**Comment by erwanlr** [comment]
Even by reducing the readme, when no other version is disclosed, it's still detected as 4.7. Well not much we can do about it :/

**Comment by lynt-smitka** [comment]
For my REST API vuln impact analysis I found a new method of WP version discovery - from install.php/upgrade.php, it works almost everytime and it beats plugins which are trying to hide it - https://lynt.cz/blog/wordpress-version-to-hide-or-not-to-hide

**Comment by anantshri** [comment]
@lynt-smitka interesting approach.

**Comment by erwanlr** [comment]
Implemented in v3.0.3
